//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace MobileCalculator.SimpleQuote {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://services.payscale.com/compensationSearch/060930", ItemName="string")]
    public class ArrayOfString : System.Collections.ObjectModel.ObservableCollection<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleQuoteResponse", Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class SimpleQuoteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MobileCalculator.SimpleQuote.CompensationSearchError ErrorField;
        
        private string LocationTypeField;
        
        private string LocationRegionField;
        
        private string CurrencyField;
        
        private string CurrencySymbolField;
        
        private double AverageField;
        
        private double MedianField;
        
        private double Percentile25Field;
        
        private double Percentile75Field;
        
        private MobileCalculator.SimpleQuote.CompensationType TypeField;
        
        private string ChartUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public MobileCalculator.SimpleQuote.CompensationSearchError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LocationType {
            get {
                return this.LocationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationTypeField, value) != true)) {
                    this.LocationTypeField = value;
                    this.RaisePropertyChanged("LocationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LocationRegion {
            get {
                return this.LocationRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationRegionField, value) != true)) {
                    this.LocationRegionField = value;
                    this.RaisePropertyChanged("LocationRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CurrencySymbol {
            get {
                return this.CurrencySymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencySymbolField, value) != true)) {
                    this.CurrencySymbolField = value;
                    this.RaisePropertyChanged("CurrencySymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Average {
            get {
                return this.AverageField;
            }
            set {
                if ((this.AverageField.Equals(value) != true)) {
                    this.AverageField = value;
                    this.RaisePropertyChanged("Average");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double Median {
            get {
                return this.MedianField;
            }
            set {
                if ((this.MedianField.Equals(value) != true)) {
                    this.MedianField = value;
                    this.RaisePropertyChanged("Median");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double Percentile25 {
            get {
                return this.Percentile25Field;
            }
            set {
                if ((this.Percentile25Field.Equals(value) != true)) {
                    this.Percentile25Field = value;
                    this.RaisePropertyChanged("Percentile25");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public double Percentile75 {
            get {
                return this.Percentile75Field;
            }
            set {
                if ((this.Percentile75Field.Equals(value) != true)) {
                    this.Percentile75Field = value;
                    this.RaisePropertyChanged("Percentile75");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public MobileCalculator.SimpleQuote.CompensationType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ChartUrl {
            get {
                return this.ChartUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ChartUrlField, value) != true)) {
                    this.ChartUrlField = value;
                    this.RaisePropertyChanged("ChartUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompensationSearchError", Namespace="http://services.payscale.com/compensationSearch/060930")]
    public enum CompensationSearchError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unexpected = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessDenied = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JobNotFound = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JobNotPreciseEnough = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughData = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidParameter = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidProfile = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidProfileID = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidJob = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidYearsOnJob = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLocation = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCountry = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidState = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCity = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCurrency = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidIncome = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBaseIncome = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidOvertime = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBonus = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCommissions = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidExperience = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDateOfBirth = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNAICSCode = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidChartType = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JobDescriptionNotFound = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TemplateNotFound = 26,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompensationType", Namespace="http://services.payscale.com/compensationSearch/060930")]
    public enum CompensationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Salary = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hourly = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TotalAnnualCompensation = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monthly = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnnualizedBasePay = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TotalCashCompensation = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bonus = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Commission = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProfitShare = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.payscale.com/compensationSearch/060930", ConfigurationName="SimpleQuote.SimpleQuoteServiceSoap")]
    public interface SimpleQuoteServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://services.payscale.com/compensationSearch/060930/GetCountries", ReplyAction="*")]
        System.IAsyncResult BeginGetCountries(MobileCalculator.SimpleQuote.GetCountriesRequest request, System.AsyncCallback callback, object asyncState);
        
        MobileCalculator.SimpleQuote.GetCountriesResponse EndGetCountries(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://services.payscale.com/compensationSearch/060930/GetStates", ReplyAction="*")]
        System.IAsyncResult BeginGetStates(MobileCalculator.SimpleQuote.GetStatesRequest request, System.AsyncCallback callback, object asyncState);
        
        MobileCalculator.SimpleQuote.GetStatesResponse EndGetStates(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://services.payscale.com/compensationSearch/060930/SuggestJobs", ReplyAction="*")]
        System.IAsyncResult BeginSuggestJobs(MobileCalculator.SimpleQuote.SuggestJobsRequest request, System.AsyncCallback callback, object asyncState);
        
        MobileCalculator.SimpleQuote.SuggestJobsResponse EndSuggestJobs(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://services.payscale.com/compensationSearch/060930/GetQuote", ReplyAction="*")]
        System.IAsyncResult BeginGetQuote(MobileCalculator.SimpleQuote.GetQuoteRequest request, System.AsyncCallback callback, object asyncState);
        
        MobileCalculator.SimpleQuote.GetQuoteResponse EndGetQuote(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountries", Namespace="http://services.payscale.com/compensationSearch/060930", Order=0)]
        public MobileCalculator.SimpleQuote.GetCountriesRequestBody Body;
        
        public GetCountriesRequest() {
        }
        
        public GetCountriesRequest(MobileCalculator.SimpleQuote.GetCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCountriesRequestBody {
        
        public GetCountriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesResponse", Namespace="http://services.payscale.com/compensationSearch/060930", Order=0)]
        public MobileCalculator.SimpleQuote.GetCountriesResponseBody Body;
        
        public GetCountriesResponse() {
        }
        
        public GetCountriesResponse(MobileCalculator.SimpleQuote.GetCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class GetCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MobileCalculator.SimpleQuote.ArrayOfString GetCountriesResult;
        
        public GetCountriesResponseBody() {
        }
        
        public GetCountriesResponseBody(MobileCalculator.SimpleQuote.ArrayOfString GetCountriesResult) {
            this.GetCountriesResult = GetCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStates", Namespace="http://services.payscale.com/compensationSearch/060930", Order=0)]
        public MobileCalculator.SimpleQuote.GetStatesRequestBody Body;
        
        public GetStatesRequest() {
        }
        
        public GetStatesRequest(MobileCalculator.SimpleQuote.GetStatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class GetStatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string country;
        
        public GetStatesRequestBody() {
        }
        
        public GetStatesRequestBody(string country) {
            this.country = country;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatesResponse", Namespace="http://services.payscale.com/compensationSearch/060930", Order=0)]
        public MobileCalculator.SimpleQuote.GetStatesResponseBody Body;
        
        public GetStatesResponse() {
        }
        
        public GetStatesResponse(MobileCalculator.SimpleQuote.GetStatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class GetStatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MobileCalculator.SimpleQuote.ArrayOfString GetStatesResult;
        
        public GetStatesResponseBody() {
        }
        
        public GetStatesResponseBody(MobileCalculator.SimpleQuote.ArrayOfString GetStatesResult) {
            this.GetStatesResult = GetStatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestJobsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestJobs", Namespace="http://services.payscale.com/compensationSearch/060930", Order=0)]
        public MobileCalculator.SimpleQuote.SuggestJobsRequestBody Body;
        
        public SuggestJobsRequest() {
        }
        
        public SuggestJobsRequest(MobileCalculator.SimpleQuote.SuggestJobsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class SuggestJobsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jobTitle;
        
        public SuggestJobsRequestBody() {
        }
        
        public SuggestJobsRequestBody(string jobTitle) {
            this.jobTitle = jobTitle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestJobsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestJobsResponse", Namespace="http://services.payscale.com/compensationSearch/060930", Order=0)]
        public MobileCalculator.SimpleQuote.SuggestJobsResponseBody Body;
        
        public SuggestJobsResponse() {
        }
        
        public SuggestJobsResponse(MobileCalculator.SimpleQuote.SuggestJobsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class SuggestJobsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MobileCalculator.SimpleQuote.ArrayOfString SuggestJobsResult;
        
        public SuggestJobsResponseBody() {
        }
        
        public SuggestJobsResponseBody(MobileCalculator.SimpleQuote.ArrayOfString SuggestJobsResult) {
            this.SuggestJobsResult = SuggestJobsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuote", Namespace="http://services.payscale.com/compensationSearch/060930", Order=0)]
        public MobileCalculator.SimpleQuote.GetQuoteRequestBody Body;
        
        public GetQuoteRequest() {
        }
        
        public GetQuoteRequest(MobileCalculator.SimpleQuote.GetQuoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class GetQuoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jobTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string country;
        
        public GetQuoteRequestBody() {
        }
        
        public GetQuoteRequestBody(string jobTitle, string city, string state, string country) {
            this.jobTitle = jobTitle;
            this.city = city;
            this.state = state;
            this.country = country;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuoteResponse", Namespace="http://services.payscale.com/compensationSearch/060930", Order=0)]
        public MobileCalculator.SimpleQuote.GetQuoteResponseBody Body;
        
        public GetQuoteResponse() {
        }
        
        public GetQuoteResponse(MobileCalculator.SimpleQuote.GetQuoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class GetQuoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MobileCalculator.SimpleQuote.SimpleQuoteResponse GetQuoteResult;
        
        public GetQuoteResponseBody() {
        }
        
        public GetQuoteResponseBody(MobileCalculator.SimpleQuote.SimpleQuoteResponse GetQuoteResult) {
            this.GetQuoteResult = GetQuoteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimpleQuoteServiceSoapChannel : MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MobileCalculator.SimpleQuote.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MobileCalculator.SimpleQuote.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MobileCalculator.SimpleQuote.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MobileCalculator.SimpleQuote.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuggestJobsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SuggestJobsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MobileCalculator.SimpleQuote.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MobileCalculator.SimpleQuote.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetQuoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetQuoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MobileCalculator.SimpleQuote.SimpleQuoteResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MobileCalculator.SimpleQuote.SimpleQuoteResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleQuoteServiceSoapClient : System.ServiceModel.ClientBase<MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap>, MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap {
        
        private BeginOperationDelegate onBeginGetCountriesDelegate;
        
        private EndOperationDelegate onEndGetCountriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetCountriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStatesDelegate;
        
        private EndOperationDelegate onEndGetStatesDelegate;
        
        private System.Threading.SendOrPostCallback onGetStatesCompletedDelegate;
        
        private BeginOperationDelegate onBeginSuggestJobsDelegate;
        
        private EndOperationDelegate onEndSuggestJobsDelegate;
        
        private System.Threading.SendOrPostCallback onSuggestJobsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetQuoteDelegate;
        
        private EndOperationDelegate onEndGetQuoteDelegate;
        
        private System.Threading.SendOrPostCallback onGetQuoteCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SimpleQuoteServiceSoapClient() {
        }
        
        public SimpleQuoteServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleQuoteServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleQuoteServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleQuoteServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetCountriesCompletedEventArgs> GetCountriesCompleted;
        
        public event System.EventHandler<GetStatesCompletedEventArgs> GetStatesCompleted;
        
        public event System.EventHandler<SuggestJobsCompletedEventArgs> SuggestJobsCompleted;
        
        public event System.EventHandler<GetQuoteCompletedEventArgs> GetQuoteCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap.BeginGetCountries(MobileCalculator.SimpleQuote.GetCountriesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCountries(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetCountries(System.AsyncCallback callback, object asyncState) {
            MobileCalculator.SimpleQuote.GetCountriesRequest inValue = new MobileCalculator.SimpleQuote.GetCountriesRequest();
            inValue.Body = new MobileCalculator.SimpleQuote.GetCountriesRequestBody();
            return ((MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap)(this)).BeginGetCountries(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileCalculator.SimpleQuote.GetCountriesResponse MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap.EndGetCountries(System.IAsyncResult result) {
            return base.Channel.EndGetCountries(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private MobileCalculator.SimpleQuote.ArrayOfString EndGetCountries(System.IAsyncResult result) {
            MobileCalculator.SimpleQuote.GetCountriesResponse retVal = ((MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap)(this)).EndGetCountries(result);
            return retVal.Body.GetCountriesResult;
        }
        
        private System.IAsyncResult OnBeginGetCountries(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetCountries(callback, asyncState);
        }
        
        private object[] OnEndGetCountries(System.IAsyncResult result) {
            MobileCalculator.SimpleQuote.ArrayOfString retVal = this.EndGetCountries(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCountriesCompleted(object state) {
            if ((this.GetCountriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCountriesCompleted(this, new GetCountriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCountriesAsync() {
            this.GetCountriesAsync(null);
        }
        
        public void GetCountriesAsync(object userState) {
            if ((this.onBeginGetCountriesDelegate == null)) {
                this.onBeginGetCountriesDelegate = new BeginOperationDelegate(this.OnBeginGetCountries);
            }
            if ((this.onEndGetCountriesDelegate == null)) {
                this.onEndGetCountriesDelegate = new EndOperationDelegate(this.OnEndGetCountries);
            }
            if ((this.onGetCountriesCompletedDelegate == null)) {
                this.onGetCountriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCountriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetCountriesDelegate, null, this.onEndGetCountriesDelegate, this.onGetCountriesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap.BeginGetStates(MobileCalculator.SimpleQuote.GetStatesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStates(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetStates(string country, System.AsyncCallback callback, object asyncState) {
            MobileCalculator.SimpleQuote.GetStatesRequest inValue = new MobileCalculator.SimpleQuote.GetStatesRequest();
            inValue.Body = new MobileCalculator.SimpleQuote.GetStatesRequestBody();
            inValue.Body.country = country;
            return ((MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap)(this)).BeginGetStates(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileCalculator.SimpleQuote.GetStatesResponse MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap.EndGetStates(System.IAsyncResult result) {
            return base.Channel.EndGetStates(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private MobileCalculator.SimpleQuote.ArrayOfString EndGetStates(System.IAsyncResult result) {
            MobileCalculator.SimpleQuote.GetStatesResponse retVal = ((MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap)(this)).EndGetStates(result);
            return retVal.Body.GetStatesResult;
        }
        
        private System.IAsyncResult OnBeginGetStates(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string country = ((string)(inValues[0]));
            return this.BeginGetStates(country, callback, asyncState);
        }
        
        private object[] OnEndGetStates(System.IAsyncResult result) {
            MobileCalculator.SimpleQuote.ArrayOfString retVal = this.EndGetStates(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStatesCompleted(object state) {
            if ((this.GetStatesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStatesCompleted(this, new GetStatesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStatesAsync(string country) {
            this.GetStatesAsync(country, null);
        }
        
        public void GetStatesAsync(string country, object userState) {
            if ((this.onBeginGetStatesDelegate == null)) {
                this.onBeginGetStatesDelegate = new BeginOperationDelegate(this.OnBeginGetStates);
            }
            if ((this.onEndGetStatesDelegate == null)) {
                this.onEndGetStatesDelegate = new EndOperationDelegate(this.OnEndGetStates);
            }
            if ((this.onGetStatesCompletedDelegate == null)) {
                this.onGetStatesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStatesCompleted);
            }
            base.InvokeAsync(this.onBeginGetStatesDelegate, new object[] {
                        country}, this.onEndGetStatesDelegate, this.onGetStatesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap.BeginSuggestJobs(MobileCalculator.SimpleQuote.SuggestJobsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSuggestJobs(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSuggestJobs(string jobTitle, System.AsyncCallback callback, object asyncState) {
            MobileCalculator.SimpleQuote.SuggestJobsRequest inValue = new MobileCalculator.SimpleQuote.SuggestJobsRequest();
            inValue.Body = new MobileCalculator.SimpleQuote.SuggestJobsRequestBody();
            inValue.Body.jobTitle = jobTitle;
            return ((MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap)(this)).BeginSuggestJobs(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileCalculator.SimpleQuote.SuggestJobsResponse MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap.EndSuggestJobs(System.IAsyncResult result) {
            return base.Channel.EndSuggestJobs(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private MobileCalculator.SimpleQuote.ArrayOfString EndSuggestJobs(System.IAsyncResult result) {
            MobileCalculator.SimpleQuote.SuggestJobsResponse retVal = ((MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap)(this)).EndSuggestJobs(result);
            return retVal.Body.SuggestJobsResult;
        }
        
        private System.IAsyncResult OnBeginSuggestJobs(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string jobTitle = ((string)(inValues[0]));
            return this.BeginSuggestJobs(jobTitle, callback, asyncState);
        }
        
        private object[] OnEndSuggestJobs(System.IAsyncResult result) {
            MobileCalculator.SimpleQuote.ArrayOfString retVal = this.EndSuggestJobs(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSuggestJobsCompleted(object state) {
            if ((this.SuggestJobsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SuggestJobsCompleted(this, new SuggestJobsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SuggestJobsAsync(string jobTitle) {
            this.SuggestJobsAsync(jobTitle, null);
        }
        
        public void SuggestJobsAsync(string jobTitle, object userState) {
            if ((this.onBeginSuggestJobsDelegate == null)) {
                this.onBeginSuggestJobsDelegate = new BeginOperationDelegate(this.OnBeginSuggestJobs);
            }
            if ((this.onEndSuggestJobsDelegate == null)) {
                this.onEndSuggestJobsDelegate = new EndOperationDelegate(this.OnEndSuggestJobs);
            }
            if ((this.onSuggestJobsCompletedDelegate == null)) {
                this.onSuggestJobsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSuggestJobsCompleted);
            }
            base.InvokeAsync(this.onBeginSuggestJobsDelegate, new object[] {
                        jobTitle}, this.onEndSuggestJobsDelegate, this.onSuggestJobsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap.BeginGetQuote(MobileCalculator.SimpleQuote.GetQuoteRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetQuote(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetQuote(string jobTitle, string city, string state, string country, System.AsyncCallback callback, object asyncState) {
            MobileCalculator.SimpleQuote.GetQuoteRequest inValue = new MobileCalculator.SimpleQuote.GetQuoteRequest();
            inValue.Body = new MobileCalculator.SimpleQuote.GetQuoteRequestBody();
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.country = country;
            return ((MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap)(this)).BeginGetQuote(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileCalculator.SimpleQuote.GetQuoteResponse MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap.EndGetQuote(System.IAsyncResult result) {
            return base.Channel.EndGetQuote(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private MobileCalculator.SimpleQuote.SimpleQuoteResponse EndGetQuote(System.IAsyncResult result) {
            MobileCalculator.SimpleQuote.GetQuoteResponse retVal = ((MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap)(this)).EndGetQuote(result);
            return retVal.Body.GetQuoteResult;
        }
        
        private System.IAsyncResult OnBeginGetQuote(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string jobTitle = ((string)(inValues[0]));
            string city = ((string)(inValues[1]));
            string state = ((string)(inValues[2]));
            string country = ((string)(inValues[3]));
            return this.BeginGetQuote(jobTitle, city, state, country, callback, asyncState);
        }
        
        private object[] OnEndGetQuote(System.IAsyncResult result) {
            MobileCalculator.SimpleQuote.SimpleQuoteResponse retVal = this.EndGetQuote(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetQuoteCompleted(object state) {
            if ((this.GetQuoteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetQuoteCompleted(this, new GetQuoteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetQuoteAsync(string jobTitle, string city, string state, string country) {
            this.GetQuoteAsync(jobTitle, city, state, country, null);
        }
        
        public void GetQuoteAsync(string jobTitle, string city, string state, string country, object userState) {
            if ((this.onBeginGetQuoteDelegate == null)) {
                this.onBeginGetQuoteDelegate = new BeginOperationDelegate(this.OnBeginGetQuote);
            }
            if ((this.onEndGetQuoteDelegate == null)) {
                this.onEndGetQuoteDelegate = new EndOperationDelegate(this.OnEndGetQuote);
            }
            if ((this.onGetQuoteCompletedDelegate == null)) {
                this.onGetQuoteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetQuoteCompleted);
            }
            base.InvokeAsync(this.onBeginGetQuoteDelegate, new object[] {
                        jobTitle,
                        city,
                        state,
                        country}, this.onEndGetQuoteDelegate, this.onGetQuoteCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap CreateChannel() {
            return new SimpleQuoteServiceSoapClientChannel(this);
        }
        
        private class SimpleQuoteServiceSoapClientChannel : ChannelBase<MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap>, MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap {
            
            public SimpleQuoteServiceSoapClientChannel(System.ServiceModel.ClientBase<MobileCalculator.SimpleQuote.SimpleQuoteServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetCountries(MobileCalculator.SimpleQuote.GetCountriesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetCountries", _args, callback, asyncState);
                return _result;
            }
            
            public MobileCalculator.SimpleQuote.GetCountriesResponse EndGetCountries(System.IAsyncResult result) {
                object[] _args = new object[0];
                MobileCalculator.SimpleQuote.GetCountriesResponse _result = ((MobileCalculator.SimpleQuote.GetCountriesResponse)(base.EndInvoke("GetCountries", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStates(MobileCalculator.SimpleQuote.GetStatesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetStates", _args, callback, asyncState);
                return _result;
            }
            
            public MobileCalculator.SimpleQuote.GetStatesResponse EndGetStates(System.IAsyncResult result) {
                object[] _args = new object[0];
                MobileCalculator.SimpleQuote.GetStatesResponse _result = ((MobileCalculator.SimpleQuote.GetStatesResponse)(base.EndInvoke("GetStates", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSuggestJobs(MobileCalculator.SimpleQuote.SuggestJobsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SuggestJobs", _args, callback, asyncState);
                return _result;
            }
            
            public MobileCalculator.SimpleQuote.SuggestJobsResponse EndSuggestJobs(System.IAsyncResult result) {
                object[] _args = new object[0];
                MobileCalculator.SimpleQuote.SuggestJobsResponse _result = ((MobileCalculator.SimpleQuote.SuggestJobsResponse)(base.EndInvoke("SuggestJobs", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetQuote(MobileCalculator.SimpleQuote.GetQuoteRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetQuote", _args, callback, asyncState);
                return _result;
            }
            
            public MobileCalculator.SimpleQuote.GetQuoteResponse EndGetQuote(System.IAsyncResult result) {
                object[] _args = new object[0];
                MobileCalculator.SimpleQuote.GetQuoteResponse _result = ((MobileCalculator.SimpleQuote.GetQuoteResponse)(base.EndInvoke("GetQuote", _args, result)));
                return _result;
            }
        }
    }
}
